### PR TITLE
Fix history panel being hidden when centered search and no quantity widget

### PR DESCRIPTION
**Pull request by Caedis**
Fixes https://github.com/GTNewHorizons/NotEnoughItems/issues/467

### CODE REVIEW

**Review by OneEyeMaker — APPROVED** [review]

**Comment by slprime** [comment]
why ignored my comment?

**Comment by Dream-Master** [comment]
@slprime so it wasnt a bug it was just disabled ?

**Comment by Caedis** [comment]
@slprime what comment?

**Comment by slprime** [comment]
image

**Comment by Caedis** [comment]
Its still pending, you never submitted it.

**Comment by slprime** [comment]
ups. I was in a hurry to work

**Comment by Caedis** [comment]
Also, did you try it in game? I tried all permutations of the 2 settings and it looked good

and as I typed that, I noticed the issue. I am not checking if the history panel is shown when returning the footer size

**Comment by Caedis** [comment]
no, line 199 handles that

**Comment by slprime** [comment]
yes, I checked. You might not have noticed that the padding at the top and bottom is slightly different depending on the settings (2 pixels difference)

**Pull request merged**
