### PR TITLE
Allow any Character to be used as Search-Prefix

### PR DESCRIPTION
**Pull request by glowredman**
https://github.com/GTNewHorizons/NotEnoughItems/pull/485 introduced a far more capable search system. However the prefix for oredict-search is now `$` while previously it was `#`. After that PR was merged there was no way to revert this back via a config setting. This PR introduces the ability to use any character as search prefix. Disabling a search parser is still possible, as well as having it always enabled. If the same prefixes are detected for multiple parsers, all but one conflicting settings are reverted to the default value.

Once this is merged, a PR to adapt the config will follow.

@slprime I added a null-check in `AnyMultiItemFilter.matches()` because I was getting NPEs there. I don't know if you forgot it or if there is an underlying issue and there shouldn't be a null filter to begin with.

### CODE REVIEW

**Comment by slprime** [comment]
1. `AnyMultiItemFilter.matches()` i fixed in https://github.com/GTNewHorizons/NotEnoughItems/pull/519
2. Where prefix settings? Hiding the prefix setting is not a good idea
image

**Comment by glowredman** [comment]
I couldn't find an `Option*` class which provides a text field, is there any?

**Comment by slprime** [comment]
>... oredict-search is now $ while previously it was # ....

no, before `#` searched by subsets, no by ore-dict. by oredict there was no search.

**Comment by slprime** [comment]
> I couldn't find an `Option*` class which provides a text field, is there any?

OptionTextField, but how to add the difference between disabled and always?

**Comment by evgengoldwar** [comment]
Why will the settings now be in the configuration file and not in the game?

**Comment by slprime** [comment]
maybe just add a setting that will switch `@` and `%`? if you are used to searching by presets using `@`

**Comment by glowredman** [comment]
> > ... oredict-search is now $ while previously it was # ....
> 
> no, before `#` searched by subsets, no by ore-dict. by oredict there was no search.

NEI 2.6.5-GTNH
grafik

**Comment by slprime** [comment]
It is also necessary not to forget about the mod https://github.com/vfyjxf/NeverEnoughCharacters/tree/1.7.10

**Comment by glowredman** [comment]
> Why will the settings now be in the configuration file and not in the game?

They were simply made accessible ingame, the config file is and always was needed to store the settings.

**Comment by glowredman** [comment]
> > I couldn't find an `Option*` class which provides a text field, is there any?
> 
> OptionTextField, but how to add the difference between disabled and always?

Always: empty String
Never: any String longer than one

**Comment by slprime** [comment]
> > > I couldn't find an `Option*` class which provides a text field, is there any?
> > 
> > 
> > OptionTextField, but how to add the difference between disabled and always?
> 
> Always: empty String Never: any String longer than one

it's not obvious

**Comment by glowredman** [comment]
> > > > I couldn't find an `Option*` class which provides a text field, is there any?
> > > 
> > > 
> > > OptionTextField, but how to add the difference between disabled and always?
> > 
> > 
> > Always: empty String Never: any String longer than one
> 
> it's not obvious

It's explained in the property's description.

**Comment by slprime** [comment]
> > > ... oredict-search is now $ while previously it was # ....
> > 
> > 
> > no, before `#` searched by subsets, no by ore-dict. by oredict there was no search.
> 
> NEI 2.6.5-GTNH grafik

NEI not added this. maybe another mod

**Comment by slprime** [comment]
but AE, JEI/REI (for new version of minecraft) and chinees mod use `$` to search by oredict. maybe best way was use $ by default?

**Comment by chochem** [comment]
> but AE, JEI/REI (for new version of minecraft) and chinees mod use `$` to search by oredict. maybe best way was use `$` by default?

I was told jei is on _disabled_ by default

**Comment by glowredman** [comment]
> > > > ... oredict-search is now $ while previously it was # ....
> > > 
> > > 
> > > no, before `#` searched by subsets, no by ore-dict. by oredict there was no search.
> > 
> > 
> > NEI 2.6.5-GTNH grafik
> 
> NEI not added this. maybe another mod
> 
> P.S. waila added this

Then we need to make sure current NEI + WAILA works

> but AE, JEI/REI (for new version of minecraft) and chinees mod use `$` to search by oredict. maybe best way was use `$` by default?

What is the default can be discussed but there must be a way to continue allowing `#` for oredict

> I was told jei is on _disabled_ by default

Afaik it is, though this discussion isn't about what the current settings are but rather what the possible settings are.

**Comment by evgengoldwar** [comment]
> > but AE, JEI/REI (for new version of minecraft) and chinees mod use `$` to search by oredict. maybe best way was use `$` by default?
> 
> I was told jei is on _disabled_ by default

Why should the best search be disable by default why not do the opposite. Who needs disable it and who likes it will keep it. Also new player will play with normal search.

**Comment by slprime** [comment]
> > but AE, JEI/REI (for new version of minecraft) and chinees mod use `$` to search by oredict. maybe best way was use `$` by default?
> 
> I was told jei is on _disabled_ by default

yes and this is very bad

**Comment by chochem** [comment]
> > > but AE, JEI/REI (for new version of minecraft) and chinees mod use `$` to search by oredict. maybe best way was use `$` by default?
> > 
> > 
> > I was told jei is on _disabled_ by default
> 
> Why should the best search be disable by default why not do the opposite. Who needs disable it and who likes it will keep it. Also new player will play with normal search.

well we are not using JEI and we are not doing that. we are doing normal search as you say.

**Comment by evgengoldwar** [comment]
> well we are not using JEI and we are not doing that. we are doing normal search as you say.

By normal search, I mean JEI Style.

**Comment by slprime** [comment]
> > > > but AE, JEI/REI (for new version of minecraft) and chinees mod use `$` to search by oredict. maybe best way was use `$` by default?
> > > 
> > > 
> > > I was told jei is on _disabled_ by default
> > 
> > 
> > Why should the best search be disable by default why not do the opposite. Who needs disable it and who likes it will keep it. Also new player will play with normal search.
> 
> well we are not using JEI and we are not doing that. we are doing normal search as you say.

but we use search in AE terminal what use JEI search

**Comment by chochem** [comment]
> > well we are not using JEI and we are not doing that. we are doing normal search as you say.
> 
> By normal search, I mean JEI Style.

JEI style would be disabled XD

**Comment by glowredman** [comment]
@chochem @evgengoldwar This PR's discussion is not about what the default are or should be. Please discuss this elsewhere. Thank you.

**Comment by chochem** [comment]
> @chochem @evgengoldwar This PR's discussion is not about what the default are or should be. Please discuss this elsewhere. Thank you.

guess you forgot to ping slprime who was the one that started this discussion.

anyway I like your changes as long as they stay in the in game settings.

**Comment by chochem** [comment]
you might also want to have a look and change the new quest that was just made about this feature according to your changes here.

**Comment by slprime** [comment]
> > @chochem @evgengoldwar This PR's discussion is not about what the default are or should be. Please discuss this elsewhere. Thank you.
> 
> guess you forgot to ping slprime who was the one that started this discussion.
> 
> anyway I like your changes as long as they stay in the in game settings.

I've listed mods that use similar syntax, like AE, if you don't like JEI

**Comment by slprime** [comment]
@glowredman, I recommend leaving the state settings as is, and adding another row of settings that will indicate prefixes. They may not be shown in the interface

**Comment by glowredman** [comment]
The Search Widget Settings GUI looks like this now:
grafik
The text fields only accept single chars and don't allow conflicts.

**Comment by glowredman** [comment]
@slprime If you want to add the Russian localizations, feel free to commit to this branch.

**Comment by slprime** [comment]
I analyzed all the possible problems that came to my mind and came up with the idea that it should be done differently.
Any other mod can add its own prefixes because exists `API.addSearchProvider()`. this will result in your checks not being able to validate prefixes correctly.

Need implementing not the prefix settings, but their substitution. Save in the settings of JSON/HashMap as "prefix" - "alias" and read it in this 2 places.

image

This will give flexibility in setting up prefixes for other providers and will also simplify the code.

P.S. Sorry you had to implement my idea from yesterday

**Pull request merged**
