### PR TITLE
Update NEIClientConfig.java

### PR DESCRIPTION
**Pull request by TataTawa**
This reduce server start time for about 1 min. Very helpful to GTNH ssp player.

### CODE REVIEW

**Comment by Glease** [comment]
I haven't written any NEI plugins, so I'm not very sure what `IConfigureNEI` will do. It makes me a bit worried about the thread safety. Have you played the game with your patch enabled for some time? If yes then I think it should be fine.

Anyhow, I think there is a better way at doing this. Instead of `ClassDiscoverer` why not just use `ASMDataTable`? It should be magnitudes faster than scanning through the jars (forge did the scanning already, so no need for another go). This should be fast enough that moving to off thread will have minimal impact.

**Comment by TataTawa** [comment]
Yes, I played the game with the patch enabled for 3 months without problem.
It is not thread safe indeed, but it reduce startup time by ~ 1 min.

**Comment by TataTawa** [comment]
I am not familiar with ASMDataTable  :<  If you know how it should be a better way

**Comment by Glease** [comment]
I wrote an article on it: https://github.com/Glease/RKB/wiki/RKB00014-ASMDataTable:-Data-of-annotations-and-interfaces

**Comment by Glease** [comment]
Nevertheless, three month is long enough to justify it as *practically safe to use*. ASMDataTable can wait when I got some more time to update my article

**Comment by Dream-Master** [comment]
glee8eToday at 2:58 AM
Anyway, that NEI pr should be good enough to be merged.

**Pull request merged**
