### PR TITLE
Мove bookmarks.ini

### PR DESCRIPTION
**Pull request by slprime**
@mitchej123 I want execute related issue. What you think if i move bookmarks.ini in save folder without config setting?

Related Issue:
https://github.com/GTNewHorizons/NotEnoughItems/issues/182

### CODE REVIEW

**Comment by boubou19** [comment]
if it's in the save folder, then where will it be located if used in MP?

**Comment by slprime** [comment]
In folder `saves/NEI/remove/{ip}/` in client side

**Comment by glowredman** [comment]
@slprime I think you mean `./saves/NEI/local/<worldname>` (SP) or `./saves/NEI/remote/<ip~port>` (MP)

**Comment by slprime** [comment]
@glowredman yes

**Comment by boubou19** [comment]
Meh if it turns the bookmark world specific i don't want that.

**Comment by glowredman** [comment]
Huh, I'd find it better world-specific

**Comment by boubou19** [comment]
this illustrates the need for a config option to have world specific/global bookmarks.

**Comment by slprime** [comment]
what is the best name for it? (I'm not very good at English)

**Comment by slprime** [comment]
what default value set?

**Comment by mitchej123** [comment]
I'd probably default to global.  Less backwards compat issues and people asking where their bookmarks went

**Comment by slprime** [comment]
I want to move bookmarks from `config/NEI` to ` save/NEI`. It creates problems anyway.

**Comment by slprime** [comment]
I could use `config/NEI/bookmarks.ini` like default

**Comment by YannickMG** [comment]
While we're having this discussion we should find a solution not just for NEI but for any mod that wants to write down data that survives config folder deletion.

**Comment by slprime** [comment]
1. By default bookmarks save globally in `./saves/NEI/global/` folder
2. If File not exists in this folder then `bookmarks.ini` copy from `./config/NEI/bookmarks.ini` (backward compatibility)
3. If set `World Specific Bookmarks = false` then bookmarks loaded from `./saves/NEI/local/<worldname>` (SP) or `./saves/NEI/remote/<ip~port>` (MP)

**Comment by mitchej123** [comment]
> 1. By default bookmarks load/save globally from/in `./saves/NEI/global/` folder
> 2. If set `World Specific Bookmarks = false` then bookmarks loaded from `./saves/NEI/local/<worldname>` (SP) or `./saves/NEI/remote/<ip~port>` (MP)
> 3. If file not exists in this folder then `bookmarks.ini` copy from `./config/NEI/bookmarks.ini` (backward compatibility) or  `./saves/NEI/global/bookmarks.ini`

This logic sounds good; will review.

**Comment by bombcar** [comment]
ip:port does that mean dns name:port or something because ips can change 

journeymap tries to use getWorldname or soemthing and it mostly works …

**Review by mitchej123 — APPROVED** [review]
Looks good, let's test on Zeta.

**Pull request merged**
