### PR TITLE
Fix some weird memory leak from changing dimensions

### PR DESCRIPTION
**Pull request by kuba6000**
Changed to ItemStackMap
before:
image

### CODE REVIEW

**Comment by Glease** [comment]
isn't the map supposed to remove the oldest entry since 20 elements? is that broken?

**Comment by kuba6000** [comment]
> isn't the map supposed to remove the oldest entry since 20 elements? is that broken?

probably, as you can see in the screenshot of memory dump

**Comment by Glease** [comment]
what java version are you using? in gt5 dev env it definitely don't do it

**Comment by kuba6000** [comment]
> what java version are you using? in gt5 dev env it definitely don't do it

jdk-22

**Comment by slprime** [comment]
Won't this create a memory problem since this method is called every time you hover over an object in world?

**Comment by slprime** [comment]
and this can't solve problem, only hide it

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/pull/583 - this PR solved the problem better

**Comment by Glease** [comment]
This map has some race condition problem. I bet this is just the fallout of that and neither PR would really work. I suggest to wrap it around synchronizedMap instead.

GT5 dev env doesn't have this issue because there is simply no contention there. The top offender lives in GC where it's calling getFluid as part of its tooltip event handler.

**Pull request closed without merging**
