### PR TITLE
Backport some of REI bookmark features

### PR DESCRIPTION
**Pull request by Quarri6343**
RIP JEI (?)

https://user-images.githubusercontent.com/39122497/189675465-143985aa-b57b-4fbb-9274-f6731540ab3c.mp4

It is better to review this after the stable release since it changes a lots of features

### CODE REVIEW

**Comment by draknyte1** [comment]
Animations should probably be configurable.

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11294#issuecomment-1244808903

**Comment by slprime** [comment]
I would leave the animation only with DnD and Add/Remove from Bookmarks.
DnD and Sorting in Bookmarks are different actions, not sure if merging is necessary

**Comment by Quarri6343** [comment]
It is difficult to catch and block every bookmark related animations
I'll leave it here for a while for the better solution

**Comment by Connor-Colenso** [comment]
I don't think disabling the animation really matters here, if your computer is such a potato you can't handle something as simple as an texture resize inside of NEI then I'd be very confused how you got the pack to run at all.

**Comment by Quarri6343** [comment]
I had a flash of inspiration and successfully disabled every "unwanted" animations in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11294
However I'm agree with Connor so I still wish to open this PR for a while

**Comment by draknyte1** [comment]
> I don't think disabling the animation really matters here, if your computer is such a potato you can't handle something as simple as an texture resize inside of NEI then I'd be very confused how you got the pack to run at all.

Animations can be visually distracting and many players turn them off.

**Comment by boubou19** [comment]
i agree with Alk here: this is so distracting and there is no real purpose to this other than fancyness. I'll likely disable it on my instance.

**Comment by GTNHAfx237v7** [comment]
Aesthetically pleasing, however I’d also turn this off after a while. So I’d welcome a config for this as well.

**Review by eigenraven — CHANGES_REQUESTED** [review]
Code looks ok, tested it locally and it looks much better with the reduced animations but there still needs to be a config to disable them entirely.

**Comment by Dream-Master** [comment]
@Quarri6343

**Review by eigenraven — APPROVED** [review]

**Pull request merged**
