### PR TITLE
Use a proper key implementation for the search cache

### PR DESCRIPTION
**Pull request by embeddedt**
**Rationale**

I play a fairly large private modpack that includes GT6 and some other mods. As I mentioned in #251, I found that searches take a very long time compared to JEI. After performing some profiling, I discovered that the main bottleneck was in `getSearchName`, due to the fact that a lot of mods implement complex logic when retrieving a tooltip. However, there was already a caching implementation that appeared to be designed to address this issue. The old approach, however, suffered from two problems.

1. It turns out that `ItemStack` does not implement `hashCode` and `equals`. This meant that attempting to retrieve a cached value from `itemSearchMap` using a different instance of the same item stack would not hit the cache.
2. The cache was cleared every time items are reloaded, however, this does not appear to be necessary.

**Changes**

* A new class, `ItemStackKey`, has been introduced that the `itemSearchNames` map makes use of. This class wraps an `ItemStack` and hashes it using its damage, item ID, and any NBT compounds. Usage of this class allows the hash map to still work  properlyeven if you close and reopen your inventory.
* `itemSearchNames` is now populated for every item in `ItemList.items` whenever that list is reloaded. It does take several more seconds for NEI to load when the world is first opened, but after that search times are instantaneous. I did not see any significant increase in memory usage when looking at F3.

I would once again appreciate your feedback in case there's an NEI implementation detail I did not consider.

### CODE REVIEW

**Comment by mitchej123** [comment]
Do you have a before/after comparison from profiling?

Also curious; I'm fairly certain NEI or CCC/CCL have an ItemStackMap that addresses exactly the short comings you mention about ItemStack and HashMap, and it was the inspiration for a similar optimization in Hodgepodge.  I'd suggest taking a look to see if that might work; I'll glance when I get a chance.

**Comment by embeddedt** [comment]
> Do you have a before/after comparison from profiling?

I had to use sampling as profiling is too slow on my machine. It's a bit tedious but I can get an after result if it's desired. Before, the sampling clearly showed that the item filtering threads were spending their time within the tooltip handlers.

>  I'm fairly certain NEI or CCC/CCL have an ItemStackMap that addresses exactly the short comings you mention about ItemStack and HashMap

Thanks; I'll look into that as it would be cleaner than a separate reimplementation.

**Comment by mitchej123** [comment]
> > Do you have a before/after comparison from profiling?
> 
> I had to use sampling as profiling is too slow on my machine. It's a bit tedious but I can get an after result if it's desired. Before, the sampling clearly showed that the item filtering threads were spending their time within the tooltip handlers.

Sampling results are fine too.  Mainly wanted a sense of the speedup.

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/blob/a7ca6c85276b9e14bd346b1225601558bc5f1d84/src/main/java/codechicken/nei/ItemStackMap.java#L20

**Comment by embeddedt** [comment]
Hmm... I take advantage of the fact that I can hash the keys with normal Java sets to do [this](https://github.com/GTNewHorizons/NotEnoughItems/pull/254/files#diff-e0769a0c77a4ab1fd3676ac2e346a8ab2410f23d46b7489ffd8ff15cd5ee05b0R168), which lets me remove any items that are still in the cache in O(1) time. That map will only let me get a list of the item stack keys, and lists don't guarantee constant removal time, as far as I know.

**Comment by embeddedt** [comment]
I think the two implementations have different merits. `ItemStackMap` seems to be useful for doing wildcard lookups where the items don't directly match. My implementation prioritizes comparing items for an exact match as efficiently as possible.

**Comment by mitchej123** [comment]
Fair enough.  Would still like to see some before/after results, but other than that seems reasonable.  Will take a closer look this afternoon as time allows.

**Comment by embeddedt** [comment]
Here are the profiler results before and after when opening the inventory panel. The improvement is very noticeable even without the profiler running if you quickly close and reopen the inventory and perform a search. In the old version, it takes several seconds, the new version performs it instantly.

I did not measure the first time the inventory is opened in order to not count initial loading operations.

Before: 2-3 seconds total spent in `getSearchName` across all threads on subsequent opens
After: 300ms spent in `getSearchName` across all threads on subsequent opens

Similar results can be seen while performing searches.

While profiling I also found that Waila's NEI filters were a substantial bottleneck and disabling them [here](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/61c0659709531c23db6ce21993680e97f38f35b3/config/Waila.cfg#L14) also provided a nice performance boost. Since NEI now has an `@mod` filter built-in, the Waila one is quite redundant.

**Comment by embeddedt** [comment]
I sped things up a bit more using `ConcurrentHashMap` instead of `synchronized` blocks; the time is now down to 100ms for `getSearchName` when you first open the inventory. These benefits should apply to each search as well.

**Comment by mitchej123** [comment]
Any more details on the waila filters? I"m not familiar with that

**Review by mitchej123 — APPROVED** [review]
Seems worth testing

**Comment by embeddedt** [comment]
By default, Waila adds some NEI filters that let you do some more advanced searches. Their implementations are [here](https://github.com/GTNewHorizons/waila/tree/aa093a4174d9c14663f497d15dd59b6e677e2597/src/main/java/mcp/mobius/waila/handlers/nei).

`ModNameFilter` was the one that came up in the profiler when I was testing my modpack. It seems that calling `nameFromStack` [in a tight loop](https://github.com/GTNewHorizons/waila/blob/aa093a4174d9c14663f497d15dd59b6e677e2597/src/main/java/mcp/mobius/waila/handlers/nei/ModNameFilter.java#L42) is not good for performance. The ore dictionary filter probably isn't seen in the profiler since it requires the search text to start with `#` to even run.

I don't use the ore dictionary filter, and recently I found out that NEI actually has a mod ID filter built-in, so I disabled the `newfilters` option in Waila's config and my searches are faster now. Some research online shows that this was a performance problem earlier in the 1.7 days but was allegedly "fixed" in a later Waila version. However, the profiler would seem to disagree.

**Pull request merged**
