### PR TITLE
Show "Delete Item" tooltip in Creative only

### PR DESCRIPTION
**Pull request by slprime**

### CODE REVIEW

**Review by Dream-Master — APPROVED** [review]

**Comment by brandyyn** [comment]
but you can still delete items in survival mode, why should it be creative only? you know how many times people try to drop items out of their inventory but then delete it instead by accident... the tooltip was good!

**Comment by slprime** [comment]
> but you can still delete items in survival mode, why should it be creative only? you know how many times people try to drop items out of their inventory but then delete it instead by accident... the tooltip was good!

By creative I meant this state:

image

**Comment by PlayfulPiano** [comment]
does this new commit / release require a change in prereqs? the last two release versions kept causing crashes whenever I opened my GUI in creative with an "applecore" not enough crashes warning.

**Comment by slprime** [comment]
> does this new commit / release require a change in prereqs? the last two release versions kept causing crashes whenever I opened my GUI in creative with an "applecore" not enough crashes warning.

applecore error not related to nei. 597 nightly works fine

**Comment by PlayfulPiano** [comment]
> > does this new commit / release require a change in prereqs? the last two release versions kept causing crashes whenever I opened my GUI in creative with an "applecore" not enough crashes warning.
> 
> applecore error not related to nei. in 597 nightly works fine

Huh, weird. The only mod differences I have btwn crashing and not crashing is using nei 24 pre vs 25 stable / 26 stable

**Pull request merged**
