### PR TITLE
Added keyboard shortcuts to NEI And More...

### PR DESCRIPTION
**Pull request by slprime**
### 1. Keyboard shortcuts
unknown

### 2. Quantity default value (it should be clearer)
unknown

### 3. Hide Quantity Input if need
| Settings | Example |
|--------------|---------------|
|unknown|hide_quantity|

### 4. Extend Tooltip (It shown if items > stackSize and stackSize > 1)
| Items | Fluid |
|--------------|---------------|
|unknown|unknown|

### 5. `shift+scroll` - scrolling ingredient (it useful if save ingredients in bookmarks)
ezgif com-gif-maker (17)

### 6. Tried to fix shadow issues with some items
| Before | After |
|--------------|---------------|
|ezgif com-gif-maker (15)|ezgif com-gif-maker (16)|

### 7. Show real item as shadow
ezgif com-gif-maker (18)

### 8. Other
1. Add Display Name to  Item and Block Dump
1. Fix selection in Presets

### CODE REVIEW

**Comment by slprime** [comment]
Related issue:
https://github.com/GTNewHorizons/NotEnoughItems/issues/268
https://github.com/GTNewHorizons/NotEnoughItems/issues/181
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10766

**Comment by miozune** [comment]
description can be hidden by button overlap

**Comment by slprime** [comment]
> description can be hidden by button overlap 

Yes :( but i don't have solution

**Comment by mitchej123** [comment]
> Yes :( but i don't have solution

Is it possible (in an easy/expedient fashion) to add a hover tooltip for obstructed ones that shows the full description?

**Comment by slprime** [comment]
image

**Comment by S4mpsa** [comment]
The stack tooltip should only show when shift is held, it is unnecessary information most of the time and breaks with very large item stacks in AE2 (This seems to be handled as Int, AE2ItemStack stack sizes are Longs).

**Comment by slprime** [comment]
1. shift added
2. AE don't return real stackSize
image
I had to hide tooltip if stackSize == Integer.MAX_VALUE

**Comment by repo-alt** [comment]
Does it make any sense to show stack count tooltip for all the slots? Looks like it makes sense only for pattern inputs/outputs? I understand that from NEI ti is not trivial to distinguish between slots, so perhaps it may be added to AE2 NEI integration from another side, e.g. in `AEBaseMEGui.handleItemTooltip ?`

**Review by Dream-Master — APPROVED** [review]
this is live on zeta now

**Pull request merged**
