### PR TITLE
fix npe

### PR DESCRIPTION
**Pull request by GlodBlock**
fix [crash-2022-09-17_20.41.39-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/9591726/crash-2022-09-17_20.41.39-client.txt)

### CODE REVIEW

**Comment by slprime** [comment]
hm... I thought it was fixed in https://github.com/GTNewHorizons/NotEnoughItems/pull/276

**Comment by GlodBlock** [comment]
but someone report this crash to me when he was using the latest nei in 2.1.2.4

**Comment by slprime** [comment]
in crash not latest version, there 2.2.21-GTNH-pre

**Comment by GlodBlock** [comment]
well it should has been fixed...

**Pull request closed without merging**
