### PR TITLE
Create Bookmarks Groups; Search Recipe

### PR DESCRIPTION
**Pull request by slprime**
Sory for google translate :)

https://github.com/GTNewHorizons/NotEnoughItems/assets/31038811/eedefc4f-84ef-4c98-acdb-f35dd239fd29

https://github.com/GTNewHorizons/NotEnoughItems/assets/31038811/bf9c5fc2-5392-4bae-9eb0-d326ad0b869b

# Create Groups in Bookmarks
1. added groups for bookmarks (1,2). To create a group, hover your cursor over a space to the left of the leftmost item. a square will appear there. grab it with `LMB` and pull it up or down. To delete a group, grab it with RMB and also drag it up or down
2. each group can have its own view, vertical (1) or horizontal (2) to switch it, click on the group with `LMB`
3. Added the ability to add multiple results to a recipe (3). first add a recipe via `shift+ctrl+a` or `shift+a`, and then another crafting result without shift.
4. added the ability to link recipes. To do this, you need to right-click on the group to link recipes in the group (4) or on the title of the bookmarks to link all the recipes on the page (5).
5. to see the calculations of related recipes without intermediate results, hold shift and point at one of the items in the group (6). Objects that will be the result of this group are marked in blue, things that this group needs to work are marked in green. items without color are intermediate items that are used in this group, but are not required for input or are not obtained at output. The quantity that is written in this state does not take into account the items that were used inside the system. in the upper left corner writes the number of cycles of the recipe
6. to delete a group entirely, hover over it and click `shift+a`

image
image
image
image
image
image

# Created Search Recipe Functionality
Closes https://github.com/GTNewHorizons/NotEnoughItems/issues/252

1. added contextual search for recipes (7). Click on the inscription with the number of pages and perform a search. This field has full basic search functionality.
2. if the tooltip does not appear, then this handler does not support search
3. in some handlers need fix it additional information
4. the search also affects the ingredients by filtering them
image

# ctrl+shift+alt+scroll
1. changes the number of recipes relative to the quantity input (right bottom).

https://github.com/GTNewHorizons/NotEnoughItems/assets/31038811/f7817e28-f17e-41ec-95ad-eea4e07f6a98

# Presets
1. Presets in mode B+ can filter recipes. it excludes those recipes that will be broken if you exclude the selected item from the game
2. speeded up the filtering

https://github.com/GTNewHorizons/NotEnoughItems/assets/31038811/9b1edcde-3bcf-4a48-a723-292b5e67500e

# AE2FC
1. NEI now works correctly with ae2fc drops and fluids. correctly changes the values in bookmarks and works Creation and Usage

https://github.com/GTNewHorizons/NotEnoughItems/assets/31038811/2ba96e9d-c646-43c6-bc2a-6eb5deebb34c

# Ability to hide specific handlers
Closes https://github.com/GTNewHorizons/NotEnoughItems/issues/180
Closes https://github.com/GTNewHorizons/NotEnoughItems/issues/406
Closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15059

You can now hide handlers added it `handler.getHandlerId()` or `handler.getOverlayIdentifier()` in `config/NEI/hiddenhandlers.csv` file

image

# Recipe Tooltip
Closes https://github.com/GTNewHorizons/NotEnoughItems/issues/408
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14360

1. how tooltip show only in Recipe Result Item, not in ingredients.
2. Added more flexible settings for tooltip display depending on the view mode of bookmarks
3. fix bug then tooltip show incorrect recipe (show first recipe of page when need second)

https://github.com/GTNewHorizons/NotEnoughItems/assets/31038811/a480cd64-55e2-4ff3-9b2f-d1d135401afa

# Closes https://github.com/GTNewHorizons/NotEnoughItems/issues/280
1. Do not show in recipes items if it hidden in NEI

# Pull all Bookmarked Items
1. key `V` on a group marker - pull all items with this group
1. `shift+V` on a group marker - pull all ingredients in this group. if group in linked mode (green) `shift+v` pull only input ingredients

# Others
1. Removed NBT flag from the settings due to its uselessness
2. Simplified the calculation of free slots in bookmarks
3. changed the algorithm for sorting items in bookmarks
4. cut out recipe search on inactive namespace
5. removed brackets from the title of bookmarks and items
6. Now right-click in bookmarks does not change item stack size. (Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14346)
7. Now in bookmarks NC item will not have a stack size.
8. Fix join same ingredients in bookmarks (example: OC Keyboard)
9. shift+scroll on ingredients, use useJEIStyledCycledIngredients to change one ingredient or similar ingredients
10. and more refactoring & optimizations

### CODE REVIEW

**Comment by Caedis** [comment]
How difficult would this be for you to split this up into multiple PRs? We prefer PRs be 1 feature at a time, and with a codebase like NEI (you are probably already aware), it can get messy for reviewers and if something needs to be reverted.

Also, can an icon be added to the recipe page to make it more obvious that the player can search from there?

1 PR for each feature, and then another for the general optimizations/fixes.

**Comment by slprime** [comment]
1. I tried splitting it into commits, but it's almost impossible.
2. icons is not my best side. it added tooltip

**Comment by Caedis** [comment]
Have you tested this with a dedicated server and in the full pack?

**Comment by slprime** [comment]
tested at least 5 people for a week

**Comment by evgengoldwar** [comment]
> Have you tested this with a dedicated server/in the full pack?
I tested every function in the full pack and found no errors

**Comment by PlayfulPiano** [comment]
What's the possibility of adding the ability to include a craftables tab which shows all the possible items you can currently craft based on your current inventory? That combined with your bookmarks feature would be a godsend for early game bulk crafting.

**Comment by slprime** [comment]
> What's the possibility of adding the ability to include a craftables tab which shows all the possible items you can currently craft based on your current inventory? That combined with your bookmarks feature would be a godsend for early game bulk crafting.

I'm not sure that the detailed functionality will be acceptable in terms of speed

**Comment by aka-zaratustra** [comment]
> Have you tested this with a dedicated server/in the full pack?

I'm a GTNH streamer. I play on a dedicated GTNH server (native, not modified). I tested all the above features on my stream with my viewers. Everything works great and is very useful.

**Comment by Caedis** [comment]
LGTM, but i want 1 more dev to review to make sure I didnt miss anything

**Review by chochem — COMMENTED** [review]
the recipe search in particular is amazing.

the main problem I see is that there is no way for players to know about these features.
Please consider some changes in that direction. Including, but not limited to:
- making the GUIs for the crafting search and for the presets actually visible
- writing quests about these features

**Comment by slprime** [comment]
| off | on |
|----------|---------|
| image | image |

**Comment by Caedis** [comment]
Looks great

**Comment by slprime** [comment]
I'm reworking the recipe search algorithm. The current one has problems with additional recipe data such as essence, voltage and more. I have an idea how to make it more flexible

**Pull request merged**
